### PR TITLE
Extend module

### PR DESCRIPTION
**Pull request by martialblog**
Hi, 

I extended the module with a tiny server_uri parameter and some new rspec/beaker tests.
Would be nice to see these tests in a Travis CI config. 

Cheers

### CODE REVIEW

**Comment by justicel** [comment]
Wow, awesome! I need to also do some cleanup myself on this module. Appreciate the pull request though and I'll take a look and merge once verified. One thing though, can you do a rebase and merge the various commits? Thanks again and I'll make sure to add credits in the module!

**Comment by martialblog** [comment]
Hi, I merged all the test stuff into one commit. That alright?

**Comment by martialblog** [comment]
Any updates on the PR?

**Comment by justicel** [comment]
Looks good! Merging. Thanks for the pull request! I'll mention your as a contributor!

**Comment by martialblog** [comment]
Yeah! Cool :+1:

**Pull request merged**
