### PR TITLE
Fix hardcoded data dir and apache group that only work on Debain

### PR DESCRIPTION
**Pull request by edestecd**
That should fix it...

### CODE REVIEW

**Comment by justicel** [comment]
@edestecd Probably should also use the http user pulled from the $::apache module rather than having that hard-coded. I can take a look at that if need be.

**Comment by edestecd** [comment]
I'm looking at the http user now and how I can get it from the apache module

**Comment by edestecd** [comment]
@justicel that takes care of the group

**Comment by justicel** [comment]
Looks great! Thanks for the pull request! I'll get it up on the forge immediately.

**Pull request merged**
